---

- name: Testing connectivity (whoami)
  command: whoami
  register: echo
  changed_when: false

- debug: msg="{{ echo.stdout }}"

- name: Testing connectivity (whoami) as root
  command: whoami
  register: echo
  become: true
  changed_when: false

- debug: msg="{{ echo.stdout }}"
